version: '3.7'

services:
  web:
    container_name: hospital_cms
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8002:8002
    networks:
      - hospitalsbox

networks:
  hospitalsbox:
